const animals = [
  '🐒 Monkey',
  '🦍 Gorilla',
  '🦧 Orangutan',
  '🐕 Dog',
  '🐩 Poodle',
  '🐺 Wolf',
  '🦊 Fox',
  '🦝 Raccoon',
  '🐈 Cat',
  '🦁 Lion',
  '🐅 Tiger',
  '🐆 Leopard',
  '🐎 Horse',
  '🦄 Unicorn',
  '🦓 Zebra',
  '🦌 Deer',
  '🦬 Bison',
  '🐂 Ox',
  '🐄 Cow',
  '🐖 Pig',
  '🐏 Ram',
  '🐐 Goat',
  '🐫 Camel',
  '🦙 Llama',
  '🦒 Giraffe',
  '🐘 Elephant',
  '🦣 Mammoth',
  '🦏 Rhinoceros',
  '🦛 Hippopotamus',
  '🐁 Mouse',
  '🐹 Hamster',
  '🐇 Rabbit',
  '🐿️ Chipmunk',
  '🦫 Beaver',
  '🦔 Hedgehog',
  '🦇 Bat',
  '🐻 Bear',
  '🐨 Koala',
  '🐼 Panda',
  '🦥 Sloth',
  '🦦 Otter',
  '🦨 Skunk',
  '🦘 Kangaroo',
  '🦡 Badger',
  '🦃 Turkey',
  '🐓 Rooster',
  '🐤 Chicken',
  '🐧 Penguin',
  '🕊️ Dove',
  '🦅 Eagle',
  '🦆 Duck',
  '🦢 Swan',
  '🦉 Owl',
  '🦤 Dodo',
  '🦩 Flamingo',
  '🦚 Peacock',
  '🦜 Parrot',
  '🐸 Frog',
  '🐊 Crocodile',
  '🐢 Turtle',
  '🦎 Lizard',
  '🐍 Snake',
  '🐉 Dragon',
  '🦕 Sauropod',
  '🦖 T-Rex',
  '🐋 Whale',
  '🐬 Dolphin',
  '🦭 Seal',
  '🐠 Fish',
  '🐡 Blowfish',
  '🦈 Shark',
  '🐙 Octopus',
  '🐌 Snail',
  '🦋 Butterfly',
  '🐛 Caterpillar',
  '🐜 Ant',
  '🐝 Honeybee',
  '🐞 Lady Beetle',
  '🦗 Cricket',
  '🪳 Cockroach',
  '🕷️ Spider',
  '🦂 Scorpion',
  '🦟 Mosquito',
  '🪰 Fly',
  '🪱 Worm',
]

const adjective = [
  'Mischievous',
  'Grumpy',
  'Outrageous',
  // '',
  'Posh',
  'Wiley',
  'Cunning',
  'Resourceful',
  'Careful',
  'Luxurious',
  'Terrifying',
  'Lazy',
  'Quick',
  'Unique',
  'Zesty',
  'Delightful',
  'Brother',
  'Official',
  'Courageous',
  'Pretty',
  'Rambunctious',
  'Great',

  'Lounging',
  'Tall',
  'Forgetful',
  'Fluffy',
  'Focussed',
  'Hip',
  'Quiet',
]

const randomProfile = () => {
  const [icon, animal] = animals[Math.floor(Math.random() * animals.length)].split(' ');
  const adj = adjective[Math.floor(Math.random() * adjective.length)];
  return { icon, name: `${adj} ${animal}` };
};

export default randomProfile;
